Soback 67 gps location search
netarchivesuite/solrwayback pull request #127
Opened 2020-11-02 09:59 UTC by jesperlauridsen

GPS location search branch

Location search added
split view after searching is done
Images bundled when serveral are close untill you zoom closer
Button added to the frontpage
Minor style adjustments to the frontpage

@thomasegense addeded for functionality check
@jorntx added for code review.

2020-11-02 11:07 UTC, jorntx approved these changes
I really like how you build the UI for this function - so neat with the screen splitter. I couldn't get the images to work (tomcat returns 400) but I think it is an index problem and the the JS code.

Great reuse of already existing functionality 👍 

Code wise there wasn't much so I will approve tight away with the following remarks:

1. There was some formatting that could be better
2. In a future version you could consider splitting some of the core Leaflet logic out sp the GpsSearch component would be more clean.

UI:
- It is a shame that you cannot trigger a search for image og search for links to image without loosing your map search state. I tried both ordinary click and open in new tab click. Bot ways result in loss of my map and results.

2020-11-02 14:14 UTC, jesperlauridsen commented on src/js/src/components/SearchBox.vue
> +        <button class="searchByFileButton" @click="showUploadFileSearch = !showUploadFileSearch">
Good catch.

2020-11-02 14:16 UTC, jesperlauridsen commented on src/js/src/components/modalComponents/GpsSearch.vue
> +      .then(result => (this.imgResults = result.response,this.mapSize = 'half', this.resultSize = 'half', this.plotImagesOnMap(this.imgResults.images), this.setLoadingStatus(false)), error => (consol
Urgh - will format. For you!

2020-11-02 14:22 UTC, jesperlauridsen commented on src/js/src/components/modalComponents/GpsSearch.vue
> +      let decision = ''
:D

2020-11-02 14:22 UTC, jesperlauridsen commented on src/js/src/components/modalComponents/GpsSearch.vue
> +        }
:+1:

2020-11-02 14:22 UTC, jesperlauridsen commented on src/js/src/components/searchResults/ImageSearchResults.vue
> +    <span>Showing <span class="highlightText">{{ imgResults.images.length }}</span> images matching query. </span>
:+1:

2020-11-03 06:32 UTC, jorntx requested changes
Corrections and additions look good but now I can't start the GPS Search. I get the following error:

<img width="680" alt="Screenshot 2020-11-03 at 07 27 32" src="https://user-images.githubusercontent.com/1721001/97955509-a120f380-1da6-11eb-9f78-8fede1452c6f.png">

2020-11-03 09:06 UTC, thomasegense approved these changes
Approved. Tested branch, did not read code.

2020-11-03 09:25 UTC, jorntx approved these changes
Works now! Let's get this show on the road.

2020-11-03 09:25 UTC, jorntx commented
Please resolve conflicts @jesperlauridsen  - thanx.

2020-11-03 09:42 UTC, merged