Soback 132 gephi export
netarchivesuite/solrwayback pull request #150
Opened 2020-11-20 13:02 UTC by jesperlauridsen

Added searchbox for gephi export.
Moved function to fix height to mixin.
Added proxy path to vue.config.js.
Added text for query examples, limitations and quick gephi guide.
styled table and setup a little bit.

2020-11-20 15:45 UTC, thomasegense requested changes
Great layout!
A few text changes. (some my own mistakes...)
2) overview tab  >- 2) Overview tab
giant compontent -> giant component 

Add a point 9:
9) Use Graph Presenter(https://github.com/statsbiblioteket/graph_presenter) to convert the SVG into a zoomable image.
(Do not show the link, make Graph Presenter as link text.

Under limitations have this line with a larger font:
Examples of linkgraphs create with SolrWayback, Gephi and Graph Presenter can be seen here 
Linkgraphs examples from the Danish Netarchive (https://labs.statsbiblioteket.dk/linkgraph/)
Again as a link with the text.

2020-11-23 07:06 UTC, jorntx approved these changes
All is good! Have one minor question.

The instructions do not make sense to me in relation to the export but I guess that this is due to my very small dataset.

2020-11-23 07:06 UTC, jorntx commented on src/js/src/mixins/SearchboxUtils.js
> +      textarea.style.height = (textarea.scrollHeight) + 'px'
Is the parenthesis needed here?

2020-11-23 13:30 UTC, jorntx approved these changes
Approved! Thanks for keeping an eye on the ngram search box 👍

2020-11-23 13:44 UTC, thomasegense approved these changes

2020-11-23 13:44 UTC, merged